version: '3.8'

services:
  oannes:
    image: goncalovalverde/oannes:latest
    container_name: oannes
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
    restart: unless-stopped
